ALTER TABLE logs
    ADD COLUMN mjlog_status INT NOT NULL DEFAULT 0 COMMENT '0:UNPROCESSED, 1:SUCCESS, 2:FAILED' AFTER played_at,
    ADD COLUMN mjlog_file_path VARCHAR(255) NULL DEFAULT NULL AFTER mjlog_status;