ALTER TABLE logs
    ADD COLUMN json_status INT NOT NULL DEFAULT 0 COMMENT '0:UNPROCESSED, 1:SUCCESS, 2:FAILED' AFTER mjlog_file_path,
    ADD COLUMN json_file_path VARCHAR(255) NULL DEFAULT NULL AFTER json_status;